name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@mahlettesfaye'
      
      - name: Get version from tag
        id: version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          CLEAN_VERSION=${TAG_VERSION#v}
          echo "version=${CLEAN_VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${CLEAN_VERSION}"
      
      - name: Update version
        run: |
            npm version ${{ steps.version.outputs.version }} --no-git-tag-version
            cat package.json
            
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GHB_TOKEN}}
